### ISSUE TITLE
Program Sign-In Page

### ISSUE THREAD

**Issue by dougdot3** [dougdot3/Sing-to-Say-Android#10]
Let's program the sign-in page so that we can do our first code with Firebase.

When you go to the sign-in view and put in your email and password, it checks with Firebase for authentication.

The code will look something like this:

`mAuth.signInWithEmailAndPassword(email, password)
.addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
            @Override
            public void onComplete(@NonNull Task<AuthResult> task) {
                if (task.isSuccessful()) {
                    // Sign in success, update UI with the signed-in user's information
                    Log.d(TAG, "signInWithEmail:success");
                    FirebaseUser user = mAuth.getCurrentUser();
                    updateUI(user);
                } else {
                    // If sign in fails, display a message to the user.
                    Log.w(TAG, "signInWithEmail:failure", task.getException());
                    Toast.makeText(EmailPasswordActivity.this, "Authentication failed.",
                            Toast.LENGTH_SHORT).show();
                    updateUI(null);
                }
            }
        });`

You can read how it works here: 

https://firebase.google.com/docs/auth/android/start

This is the code to replicate from iOS for now (there are some additional steps we will do later):

`[[FIRAuth auth] signInWithEmail:self->_emailStr
                           password:self->_passwordStr
                           completion:^(FIRAuthDataResult * _Nullable authResult,
                                      NSError * _Nullable error) {
                             if (error) {
                                 // [START_EXCLUDE]
                                 [self showErrorAlertWithMessage:@"Invalid login. Please try again." ];
                                 [self.activityIndicator setHidden:TRUE];
                                 [self.activityIndicator stopAnimating];
                                 [self.loginLabel setHidden:FALSE];
                                 [self.loginButton setHidden:FALSE];
                                 [self.loginActivityButton setHidden:FALSE];
                                 // [END_EXCLUDE]
                                 return;
                             }else{
                                 [self.activityIndicator setHidden:TRUE];
                                 [self.activityIndicator stopAnimating];
                                 [self.loginLabel setHidden:FALSE];
                                 [self.loginButton setHidden:FALSE];
                                 [self.loginActivityButton setHidden:FALSE];
                                 [self performSegueWithIdentifier:@"segueToLanding" sender:self];
                             }
                         }];
}`

**Comment by dougdot3** [comment]
P.S. I don't know why there are no line breaks - you can edit the issue to see the code with line breaks.

**Comment by jwchoo-81** [comment]
Is there a mock account we can use to ensure that the sign is in successful ?

**Comment by dougdot3** [comment]
doug+stelian@popyn.app PW Mariah
