### ISSUE TITLE
Add a button over video on landing page

### ISSUE THREAD

**Issue by dougdot3** [dougdot3/Sing-to-Say-Android#108]
When you first load the app, you come to a page which auto plays a video. When you tap on the video, it should stop, when you tap again it should resume,

Code on iOS:

```
- (IBAction)clickPause:(id)sender {
    if(self.isPaused){
        [self.player play];
        self.isPaused = FALSE;
    }else{
        [self.player pause];
        self.isPaused = TRUE;
    }
}
```

**Comment by dougdot3** [comment]
This is showing as complete but it's not working in my version.

**Comment by dougdot3** [comment]
In iOS this is just a big invisible button. You added video controls instead. Can we turn it into an invisible button like the code above OR make the controls smaller?

It also seems like this creates an issue with the Samsung menu bar showing up and blocking the sign-in button at the bottom of the page:

![image](https://user-images.githubusercontent.com/7491145/145916660-b0efe7b8-0bd7-495e-aca8-e89c8343a25f.png)

**Comment by dougdot3** [comment]
Yes...confirmed - when you tap the controls it opens up the bottom bar. Is there a way to prevent this?

**Comment by choohs** [comment]
![welcome](https://user-images.githubusercontent.com/52901114/146415022-c0642380-c054-455e-953f-043711baabd7.jpg)
Can't completely hide the navigation bar at the bottom but was able to make it overlay the screen with an invisible background instead of white.
