### ISSUE TITLE
Loading Screen Code: Determine if User Is Logged In

### ISSUE THREAD

**Issue by dougdot3** [dougdot3/Sing-to-Say-Android#11]
On the loading screen when the music is playing, we determine whether there is a user logged in to the app.

If NO: Go to the welcome screen
If YES: Go to the landing page..... NOTE....if their email is NOT validated, we show the email screen on top of the landing page

To determine whether the user is logged in, we use a Firebase authentication call, as seen here:

 https://firebase.google.com/docs/auth/android/start

```
@Override
public void onStart() {
    super.onStart();
    // Check if user is signed in (non-null) and update UI accordingly.
    FirebaseUser currentUser = mAuth.getCurrentUser();
    if(currentUser != null){
        reload();
    }
}

```

This is the code in iOS. 

```
if (![FIRAuth auth].currentUser) {
            NSLog(@"There is no current user in loading so we go to sign-up flow");
           [self performSegueWithIdentifier:@"segueFromLoadingToLogin" sender:self];
        }else{
          [self performSegueWithIdentifier:@"goToLanding" sender:self];
        }

```

**Comment by jwchoo-81** [comment]
doug+stelian@popyn.app PW Mariah
