### ISSUE TITLE
Constraint issues with privacy policy

### ISSUE THREAD

**Issue by dougdot3** [dougdot3/Sing-to-Say-Android#110]
"This is the bottom of the page- cannot scroll further
Note also top of page. probably due to the model of the tablet I've got which is small.Definitely a sizing issue, probably due to the model of the tablet I've got which is small."

![unnamed](https://user-images.githubusercontent.com/7491145/144883661-24155687-c8fb-4f2a-b59e-6b03757aa2fa.jpg)

**Comment by jwchoo-81** [comment]
![image](https://user-images.githubusercontent.com/50019463/145055015-f4363b36-7679-4103-af13-9c3dd2c6e920.png)
Don't see a top constraint issue. Only issue with the button

**Comment by dougdot3** [comment]
We are still seeing this issue on smaller screens. The top text is truncated and the bottom button is not visible. Please check again using simulator for smaller screens and send a screen shot of what you see. This is what Neil currently sees on his smaller Samsung:
<img width="508" alt="Screen Shot 2021-12-10 at 9 35 42 AM" src="https://user-images.githubusercontent.com/7491145/145590881-0b5b5e34-786c-4dce-b1e0-695356245e25.png">
