### ISSUE TITLE
Layout issue with registration

### ISSUE THREAD

**Issue by dougdot3** [dougdot3/Sing-to-Say-Android#111]
See screenshot for small screens:

![unnamed2](https://user-images.githubusercontent.com/7491145/144886078-dc03f8af-9d5c-429d-ba4b-07acbecba3f0.jpg)

**Comment by jwchoo-81** [comment]
![7-inch](https://user-images.githubusercontent.com/50019463/145051277-b54c8b8e-fdf3-4928-ba8e-8f9c6e88b2c8.PNG)

There's no issue with 7-inch tablet , screen shot provided with 600 x 1024 mdpi

**Comment by jwchoo-81** [comment]
Couldn't replicate the issue, tested on an A7 Lite.
