### ISSUE TITLE
One last step page constraint issue

### ISSUE THREAD

**Issue by dougdot3** [dougdot3/Sing-to-Say-Android#115]
Fix the constraints on the left and right because Neil is seeing text go off the page:
<img width="497" alt="Screen Shot 2021-12-10 at 10 17 48 AM" src="https://user-images.githubusercontent.com/7491145/145597312-af38740f-b364-42ed-bf2f-a66083da9040.png">

**Comment by jwchoo-81** [comment]
![photo_2021-12-13_01-00-42](https://user-images.githubusercontent.com/50019463/145721842-c3eddab7-3cc1-4ed8-9856-75f941daff5a.jpg)

This is an A7 Lite, we are unable to replicate the issue above. We've also attached a 7 inch screen, which is smaller than the A7 lite.,

![nex7](https://user-images.githubusercontent.com/50019463/145721937-532576fb-1be2-42f2-8525-df35e92cfa47.jpg)

**Comment by jwchoo-81** [comment]
Both seems fine, on both cases.
Is neil testing on an even smaller screen ?
