### ISSUE TITLE
Tweak constraints for Landing Page

### ISSUE THREAD

**Issue by dougdot3** [dougdot3/Sing-to-Say-Android#117]
On smaller screens the constraints create a bit of an "off" layout. This is how it looks:

<img width="1108" alt="Screen Shot 2021-12-10 at 12 00 49 PM" src="https://user-images.githubusercontent.com/7491145/145612647-6313bb0a-930c-4f7c-8e88-fa40e68e3127.png">

- Logo stays too large, it should scale down
- Learn It button looks too small, probably because of logo constraints
- Buttons aren't as "neat" on smaller screens and text is crowded inside button

**Comment by dougdot3** [comment]
Please provide screen shot of A7Lite from simulator.

**Comment by choohs** [comment]
![main](https://user-images.githubusercontent.com/52901114/146415433-dfc64293-d173-4750-b5b4-9b3f8f53353e.JPG)
This is what it looks like on my A7 lite emulator.
