### ISSUE TITLE
Replace Terms of Service

### ISSUE THREAD

**Issue by dougdot3** [dougdot3/Sing-to-Say-Android#120]
Replace the terms and conditions with the attached

[Sing to Say Foundations Privacy PolicyFINAL Dec 13.docx](https://github.com/dougdot3/Sing-to-Say-Android/files/7707979/Sing.to.Say.Foundations.Privacy.PolicyFINAL.Dec.13.docx)
.

**Comment by dougdot3** [comment]
This should be put in as text. Try to make it look as much like the word doc as possible. But there's only so much you can do.

**Comment by dougdot3** [comment]
There will be one final revision to this. Please hold until you receive the final. There is a small wording change. 

Note that the file was misnamed. It said "Privacy Policy" but it's actually Terms of Use.

**Comment by choohs** [comment]
![image](https://user-images.githubusercontent.com/52901114/146642135-0a274db0-d734-4e67-a338-ca55bc31ce5e.png)
![image](https://user-images.githubusercontent.com/52901114/146642159-0579338c-7b48-44c5-bee5-03668cc42fd3.png)

Ok, this is how the layout looks like on the 7" tablet. Tried to replicate the word doc as closely as I could.

**Comment by dougdot3** [comment]
Lovely. Done.
