### ISSUE TITLE
Add hero image to packs

### ISSUE THREAD

**Issue by dougdot3** [dougdot3/Sing-to-Say-Android#33]
When a user clicks on a pack icon, it takes them to the ITEMS. For example, you demonstrated how we click on CORE and see a list of CORE ITEMS:

<img width="896" alt="Screen Shot 2021-10-13 at 12 04 49 PM" src="https://user-images.githubusercontent.com/7491145/137188566-7f6e919d-67ca-45b0-aba5-ddb2b3c820e4.png">

Once you are on the ITEM screen, the top "hero" section should change. So, for example, CORE would show:

![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2021-10-13 at 12 06 27](https://user-images.githubusercontent.com/7491145/137188773-be3c37a3-3f63-42a1-a065-3130f2e22de2.png)

The image is from the PACK:

<img width="698" alt="Screen Shot 2021-10-13 at 12 08 24 PM" src="https://user-images.githubusercontent.com/7491145/137189055-6a78def3-b386-4a21-92da-27001ad670f0.png">

Field name:
`heroImageUrl`

**Comment by jwchoo-81** [comment]
completed
