### ISSUE TITLE
Email verification screen doesn't disappear

### ISSUE THREAD

**Issue by dougdot3** [dougdot3/Sing-to-Say-Android#47]
In Firebase, a "listener" is attached to a node:

https://firebase.google.com/docs/database/admin/retrieve-data

This results in code like:

```
// Get a reference to our posts
final FirebaseDatabase database = FirebaseDatabase.getInstance();
DatabaseReference ref = database.getReference("server/saving-data/fireblog/posts");

// Attach a listener to read the data at our posts reference
ref.addValueEventListener(new ValueEventListener() {
  @Override
  public void onDataChange(DataSnapshot dataSnapshot) {
    Post post = dataSnapshot.getValue(Post.class);
    System.out.println(post);
  }

  @Override
  public void onCancelled(DatabaseError databaseError) {
    System.out.println("The read failed: " + databaseError.getCode());
  }
});
```

If the listener is attached, you can detect changes to the data. That's what we need on the email verifications screen.

**Current behaviour:**
- User registers
- User is taken to the "One last step, please check your email"
- When their email is verified, the screen STAYS

**Desired behaviour**
- For step 3 above, when emailVerified changes from 0 to 1 the user should be taken to the home page of the app

**Comment by jwchoo-81** [comment]
I am still looking into this issue, I am suspecting it is the Android Life Cycle issue. Will move my codes up and test again.

**Comment by dougdot3** [comment]
No, I don't think it is. It's how you're handling Firebase. The node needs to be kept alive. Let's discuss and you can show me the code.

**Comment by jwchoo-81** [comment]
sure, we can have a call to discuss on how it is being done.
