### ISSUE TITLE
Video extension file doesn't install

### ISSUE THREAD

**Issue by dougdot3** [dougdot3/Sing-to-Say-Android#50]
It's not clear exactly what the steps are supposed to be and it sounds like it works on your end, but the video does NOT play when clicking on an item. Instead, you get a 'video unavailable' notice:

![Screenshot_20211025-172501_Sing To Say](https://user-images.githubusercontent.com/7491145/138773427-e501ac88-ab6b-4d7a-a6bb-0d27e3acaaed.jpg)

Is there some sort of process that needs to happen to install the videos? I notice that the app file size is the same and no additional prompts happen. Was this tested on a physical device? (Did you get one yet? :) )

**Comment by jwchoo-81** [comment]
This has been resolved with Google Play Console. You have to download from Google Play Console.
Thanks
