### ISSUE TITLE
Play song when user clicks on name at top of screen in Check It

### ISSUE THREAD

**Issue by dougdot3** [dougdot3/Sing-to-Say-Android#57]
We give the user one more reminder of the song by playing the .wav file for that song if they click on the name at the top of the screen:

![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2021-11-02 at 08 43 21](https://user-images.githubusercontent.com/7491145/139904779-1a9be8c5-f015-473c-b64b-3a28592a5d4e.png)

It's important to note that how it appears in the database on Firebase needs to be appended with m_ and end with .wav like below:

```
//  self.songFileName = [item valueForKey:@"longSongFileName"];

-(void)playFullSong{
    NSString * fileName = [NSString stringWithFormat:@"%@%@%@", @"m_", self.songFileName, @".wav"];
    NSString *finalFileName = [fileName substringToIndex:[fileName length]-6];
   // NSLog(@"Ready to play song %@", fileName);
    [SimpleAudioPlayer playFile:finalFileName withCompletionBlock:^(BOOL finished) {
    }];
}
```

**Comment by jwchoo-81** [comment]
Sorry, but do you have the wav files ? Is it going to be fetched locally or how is it going to fetch the assets?
