### ISSUE TITLE
URGENT FIX Landing Page

### ISSUE THREAD

**Issue by dougdot3** [dougdot3/Sing-to-Say-Android#60]
We STILL have an issue with how the video screen constraints are set up. This is an urgent issue. They can not see any of the app at all because they can't even click the buttons.

See:

<img width="615" alt="Screen Shot 2021-11-03 at 12 51 30 PM" src="https://user-images.githubusercontent.com/7491145/140174193-0ba3d25d-1704-41f7-ad95-62ee397f50cf.png">

**Comment by jwchoo-81** [comment]
We are unable to emulate it.
I've attached 2 image showcasing the Galaxy Tab A7 Lite Login screen and the specification.
The third image is from Samsung Official Site ( [https://developer.samsung.com/galaxy-emulator-skin/galaxy-tab.html](url) )
![photo_2021-11-04_03-53-53](https://user-images.githubusercontent.com/50019463/140189953-76ebef64-36a8-4deb-82d6-a825853fa717.jpg)
![photo_2021-11-04_04-46-03](https://user-images.githubusercontent.com/50019463/140190058-8e859d3e-56d7-46d7-b54e-739921ce6f8e.jpg)
![image](https://user-images.githubusercontent.com/50019463/140190113-bd4d46f7-f802-423c-87a4-b73980961cb5.png)
