### ISSUE TITLE
Design Email Verification Screen

### ISSUE THREAD

**Issue by dougdot3** [dougdot3/Sing-to-Say-Android#9]
One last screen before we do the actual app! When a user signs up, they need to verify their email. Before they verify their email, they are not allowed to use the app. And so they see this screen:

<img width="599" alt="Screen Shot 2021-08-24 at 10 38 21 AM" src="https://user-images.githubusercontent.com/7491145/130636917-8b662301-b915-4dc5-8c44-00dae23ad4cd.png">

The main image required:

![sub_gift@2x](https://user-images.githubusercontent.com/7491145/134259641-3e6a7c07-c98b-456a-b680-00bf1b4e2476.png)

Other images (button, logo) have already been used on other screens.

**Comment by dougdot3** [comment]
Oh - one change....make the font in the headline dark blue instead of white, and make the buttons 50% of the size. I will be making these changes in iOS also.

**Comment by dougdot3** [comment]
Here is the background:

![Rectanglev green@2x](https://user-images.githubusercontent.com/7491145/134366610-8a80363d-6c41-43ff-bdb3-71fb8ee4b6dc.png)

**Comment by jwchoo-81** [comment]
Completed, Issued Pull request
